"use strict";
exports.__esModule = true;
exports.Amenities = {
    airConditioning: function (parent) { return parent.airConditioning; },
    babyBath: function (parent) { return parent.babyBath; },
    babyMonitor: function (parent) { return parent.babyMonitor; },
    babysitterRecommendations: function (parent) { return parent.babysitterRecommendations; },
    bathtub: function (parent) { return parent.bathtub; },
    breakfast: function (parent) { return parent.breakfast; },
    buzzerWirelessIntercom: function (parent) { return parent.buzzerWirelessIntercom; },
    cableTv: function (parent) { return parent.cableTv; },
    changingTable: function (parent) { return parent.changingTable; },
    childrensBooksAndToys: function (parent) { return parent.childrensBooksAndToys; },
    childrensDinnerware: function (parent) { return parent.childrensDinnerware; },
    crib: function (parent) { return parent.crib; },
    doorman: function (parent) { return parent.doorman; },
    dryer: function (parent) { return parent.dryer; },
    elevator: function (parent) { return parent.elevator; },
    essentials: function (parent) { return parent.essentials; },
    familyKidFriendly: function (parent) { return parent.familyKidFriendly; },
    freeParkingOnPremises: function (parent) { return parent.freeParkingOnPremises; },
    freeParkingOnStreet: function (parent) { return parent.freeParkingOnStreet; },
    gym: function (parent) { return parent.gym; },
    hairDryer: function (parent) { return parent.hairDryer; },
    hangers: function (parent) { return parent.hangers; },
    heating: function (parent) { return parent.heating; },
    hotTub: function (parent) { return parent.hotTub; },
    id: function (parent) { return parent.id; },
    indoorFireplace: function (parent) { return parent.indoorFireplace; },
    internet: function (parent) { return parent.internet; },
    iron: function (parent) { return parent.iron; },
    kitchen: function (parent) { return parent.kitchen; },
    laptopFriendlyWorkspace: function (parent) { return parent.laptopFriendlyWorkspace; },
    paidParkingOffPremises: function (parent) { return parent.paidParkingOffPremises; },
    petsAllowed: function (parent) { return parent.petsAllowed; },
    pool: function (parent) { return parent.pool; },
    privateEntrance: function (parent) { return parent.privateEntrance; },
    shampoo: function (parent) { return parent.shampoo; },
    smokingAllowed: function (parent) { return parent.smokingAllowed; },
    suitableForEvents: function (parent) { return parent.suitableForEvents; },
    tv: function (parent) { return parent.tv; },
    washer: function (parent) { return parent.washer; },
    wheelchairAccessible: function (parent) { return parent.wheelchairAccessible; },
    wirelessInternet: function (parent) { return parent.wirelessInternet; }
};
